server:
  port: 8086

spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/payme-db
    username: postgres
    password: @123456@
    initialize: true
    maxActive: 3

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob.non_contextual_creation: true
  sql:
    init:
      mode: always
      continue-on-error: true
      platform: postgresql

app-config:
  name: payme-api
  version: 1.0.0
  description: API de integração com o serviço de pagamentos da api.payulatam.com
  url: http://localhost:8086/

  schedulers:
    transacoes:
      atualizar-transacoes-cada-20-minutos: "0 0/20 * * * *"

######################################################################
##################INTEGRAÇÃO COM API.PAYULATAM.COM####################
######################################################################
payulatam:
  api_keys:
    teste: teste
    producao: teste
  base-uri: https://api.payulatam.com/payments-api/4.0/service.cgi
  transacoes:
    uri: ${pagarme.base-uri}/transactions
  cartoes:
    uri: ${pagarme.base-uri}/cards
  estornos:
    uri: ${pagarme.base-uri}/refunds

jwt:
  secret: Y2FkZWlyYS1saXZyZS11c3VhcmlvLWFwaS1kZXNlbnZvbHZpbWVudG8=
