server:
  port: ${PORT:8085}

spring:

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  main:
    allow-bean-definition-overriding: true

  application:
    name: product-api

  redis:
    host: localhost
    port: 6379
    cache:
      type: redis
    redis:
      time-to-live: 60_000
    key-prefix: product-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:product-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:@123456@}
    initialize: true
    maxActive: 3

  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:product-db}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:@123456@}
    baselineOnMigrate: true
    locations: classpath:db/migration
    enabled: true
    fail-on-missing-locations: true
    executeInTransaction: true

  sql:
    init:
      continue-on-error: true
      platform: postgresql
      mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    open-in-view: true

  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USER:admin}
    password: ${RABBIT_MQ_PASSWORD:@123456@}

app-config:

  services:
    sales: http://${SALES_HOST:localhost}:${SALES_PORT:8084}

  secrets:
    api-secret: ${API_SECRET:YXV0aC1hcGktc2VjcmV0LWRldi0xMjM0NTY=}

  rabbit:
    exchange:
      product: product.topic

    routingKey:
      product-stock: product-stock-update.routingKey
      sales-confirmation: sales-confirmation.routingKey

    queue:
      product-stock: product-stock-update.queue
      sales-confirmation: sales-confirmation.queue

springdoc:
  pathsToMatch:
    - /auth/**
    - /api/**
    - /swagger-ui/**
  swagger-ui:
    use-root-path: true
    enabled: true
  show-actuator: true

logging:
  file:
    name: product-api.log
    path: D:/workspace/ms-sales/ELK_Stack/elk_product_api.log
